version: "3.9"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: fintonic
      MONGO_INITDB_ROOT_PASSWORD: fintonic123
    ports:
      - "27017:27017"
  taskmanager:
    image: fintonic/taskmanager
    depends_on:
      - mongo
    ports:
      - "8080:8080"